### ISSUE TITLE
'소스' 기능에 <iframe> 태그 추가

### ISSUE THREAD

**Issue by mireleader** [xpressengine/plugin-ckeditor#20]
CkEditor를 이용해서.. 게시글 내에.. YouTube 동영상을 삽입하려고..

<iframe> 태그 넣으려는데..
반영이 안됩니다.

어느부분 수정하면 가능할까요?

**Comment by mintplo** [comment]
CKEditor 쪽 문제라기보다는 HTMLPrufier 에서 iframe 태그를 거르기 때문에 그런것 같습니다.

저도 현재 아래와 같은 youtube 영상을 첨부하면 해당 iframe만 filtering 되어 보이지 않습니다.
<iframe width="560" height="315" src="https://www.youtube.com/embed/iCpxEONR1r8" frameborder="0" allowfullscreen></iframe>

**Comment by mireleader** [comment]
소스코드 중 어디를 수정하면 되는지 아시나요?

**Comment by mintplo** [comment]
@mireleader HTML Purifier 설정을 좀 변경해보면서 테스트 해봤는데 저도 해결이 안되어서 Q&A에 글을 올려놨습니다. https://www.xpressengine.io/qna/%EC%9C%A0%ED%88%AC%EB%B8%8C-%EC%82%BD%EC%9E%85-%EA%B4%80%EB%A0%A8-%EB%AC%B8%EC%A0%9C 급하신거 아니면 이 쪽 thread 참고하시면 될것 같습니다.

**Comment by mintplo** [comment]
@mireleader core/src/Xpressengine/Support/Purifier.php 에서 아래와 같이 변경했습니다. Board 쪽이나 여타 다른 곳은 Support/Purifier.php 를 사용하고 있네요.

Doctype을 XHTML strict로 설정하니까 XHTML strict에서는 해당 엘리먼트를 사용할 수 없는지... iframe을 아예 사용할 수 없게 됩니다.

커뮤니티 사이트를 운영하시고자 한다면 Core의 Purifier 를 건드는건 한번 더 생각해보셔야할것 같습니다.

```php
$this->config->loadArray([
            'Core.Encoding' => 'UTF-8',
            'Cache.SerializerPath' => storage_path('framework/htmlpurifier/support'),
            'HTML.Allowed' => 'div,b,strong,i,em,a[href|title],ul,ol,li,p[style],h1,h2,h3,h4,hr' .
                ',br,span[style|class|data-download-link|contenteditable]' .
                ',img[width|height|alt|src],table[summary],tbody,th[abbr],tr,td[abbr]',
            'CSS.AllowedProperties' => 'font,font-size,font-weight,font-style,font-family' .
                ',text-decoration,padding-left,color,background-color,text-align',
            'AutoFormat.AutoParagraph' => true,
            'AutoFormat.RemoveEmpty' => true,
            "HTML.SafeIframe" => true,
            "URI.SafeIframeRegexp" => "%^(http://|https://|//)(www.youtube.com/embed/|player.vimeo.com/video/)%",
        ]);
        $this->config->set('HTML.AllowedElements', ['a', 'b', 'p', 'i', 'em', 'br', 'div', 'img', 'strong', 'iframe']);
        $this->config->set('HTML.AllowedAttributes', [
            'a.href', 'img.src', '*.alt', '*.title', '*.border', 'a.target', 'a.rel',
            'iframe.src', 'iframe.width', 'iframe.height', 'iframe.frameborder',
        ]);
```

**Comment by mireleader** [comment]
@mintplo 감사합니다.
위의 소스로 적용해보겠습니다.
