### ISSUE TITLE
이미지 리사이징이 안되는 문제

### ISSUE THREAD

**Issue by mintplo** [xpressengine/plugin-ckeditor#21]
업로드한 이미지를 본문 반영하고

이미지 크기나 높이 속성을 에디터에서 제공하는 이미지 속성을 수정해도 실제로 반영이 되지 않는것 같습니다.

OS: Mac OSX
Browser: Chrome

**Comment by jhyeon1010** [comment]
xpressengine/xpressengine#455 에서 처리하겠습니다.

**Comment by seungmanchoi** [comment]
purifier img추가로 수정 배포됨.
