### ISSUE TITLE
이미지 편집 툴 사용 시 오류

### ISSUE THREAD

**Issue by smaker** [xpressengine/plugin-ckeditor#62]
![캡처2](https://user-images.githubusercontent.com/1732040/58923242-ce184380-8779-11e9-8e0b-9089245aa2a7.PNG)

에디터에서 이미지 편집 툴을 켜면 위와 같은 에러가 발생합니다.

**Comment by woongbin** [comment]
제보해주신 내용을 수정해서 1.0.2 버전을 배포했습니다.
업데이트 하시면 정상적으로 사용 가능합니다.
감사합니다.
