### ISSUE TITLE
PHP 7.4에서 설치가 되지 않거나 동작하지 않음

### ISSUE THREAD

**Issue by woongbin** [xpressengine/plugin-ckeditor#66]
PHP 7.4에서 설치가 되지 않거나 동작하지 않음

**Comment by superior0528** [comment]
그러면 latest version 을 설치하면, 해결된건가요? 4일전쯤에 7.4환경에서 했는데 안되서요, 이 내용은 16일전에 해결된거 같은데 말이죠...
