### ISSUE TITLE
게시판 상세 설정 페이지 오타

### ISSUE THREAD

**Issue by cansmile** [xpressengine/plugin-ckeditor#71]
‘하단 공통 내용’ 항목과 ‘하단 글보기 내용’ 항목 사이에 ‘상단 공통 내용 목록에만 사용’이라는 제목으로 되어 있네요. 아마 상단‧‧‧ 것을 복사해서 수정하시면서 빠뜨리신듯 하네요.
![2020040100001](https://user-images.githubusercontent.com/459021/78098953-7428ee80-741b-11ea-840d-1bdd0f935ab6.png)

**Comment by bi-kim** [comment]
<img width="913" alt="스크린샷 2021-12-21 오후 8 45 33" src="https://user-images.githubusercontent.com/10782883/146924982-6d3675c6-6a87-4b26-a4de-724c4006e95f.png">
