### ISSUE TITLE
편집기에 파일 끌었을 때 ‘최대 업로드‧‧‧‧’ 메시지

### ISSUE THREAD

**Issue by cansmile** [xpressengine/plugin-ckeditor#72]
편집기 하단에 첨부하면 정상적으로 업로드되는 파일도 편집기 문자영역에 떨구면 오류메시지가 나오네요.
php7.0 xe호스팅 이용 중입니다.
문자영역에 떨궜을 때 안 된다면 차라리 ‘첨부기능을 이용해주세요’라던지 첨부 기능이 활성화되지 않은 경우에는 ‘첨부가 안 됩니다’를 보여주는게 더 나은거 아닐까요?
![2020040100002](https://user-images.githubusercontent.com/459021/78099176-0b8e4180-741c-11ea-9d64-65eda7de6379.png)

**Comment by bi-kim** [comment]
XpressEngine 3.0.14 Developer Version 이상에서 해결된 모습을 볼 수 있습니다.
https://github.com/xpressengine/xpressengine/issues/1359
