### ISSUE TITLE
미디어 라이브러리 첫 번째 항목이 드롭존 아래에 숨음

### ISSUE THREAD

**Issue by cansmile** [xpressengine/plugin-ckeditor#75]
제목대로에요.
![2020040400009](https://user-images.githubusercontent.com/459021/78420705-8198df80-768c-11ea-9803-872002e8673f.png)
스샷 아래에 희미하게 선택된 항목이 옆은 하늘색 배경으로 선택되어 있는게 보이실겁니다.

**Comment by bnu** [comment]
fixed https://github.com/xpressengine/xpressengine/issues/1129
